version: '3.8'
services:
  postgres:
    image: postgres:16.1-alpine3.19
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: postgres
