server:
  port: ${GATEWAY_APP_PORT:8080}

spring:
  main:
    web-application-type: reactive
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
      routes:
        - id: storage
          uri: http://${STORAGE_APP_HOST:localhost}:${STORAGE_APP_PORT:8082}/
          predicates:
            - Path=/api/v1/files/**
        - id: forum
          uri: http://${FORUM_APP_HOST:localhost}:${FORUM_APP_PORT:8084}/
          predicates:
            - Path=/api/v1/**
        - id: auth
          uri: http://${AUTH_APP_HOST:localhost}:${AUTH_APP_PORT:8085}/
          predicates:
            - Path=/api/v1/**
