server:
  port: 8080

spring:
  main:
    web-application-type: reactive
  cloud:
    gateway:
      routes:
        - id: storage
          uri: http://localhost:8082/
          predicates:
            - Path=/api/v1/files/**
