server:
  port: ${GATEWAY_APP_PORT:8080}

spring:
  main:
    web-application-type: reactive
  cloud:
    gateway:
      routes:
        - id: storage
          uri: http://${STORAGE_APP_HOST:localhost}:${STORAGE_APP_PORT:8082}/
          predicates:
            - Path=/api/v1/files/**
